version: '3.1'
services:
  dialog:
    build:
      context: ./dialog
      dockerfile: Dockerfile
    container_name: rock-paper-scissors_dialog
    env_file: .env
    secrets:
      - google_service_account.json

  jovo:
    build:
      context: .
      dockerfile: ./jovo/Dockerfile
      args:
        - PROJECTID=${PROJECTID}
        - GOOGLE_APPLICATION_CREDENTIALS_SOURCE=${GOOGLE_APPLICATION_CREDENTIALS_SOURCE}
        - FORCERERUNFROMHERE=${FORCERERUNFROMHERE}
    container_name: rock-paper-scissors_jovo
    env_file: .env
    secrets:
      - google_service_account.json
    
secrets:
  google_service_account.json:
    file: ./service_account.json
